# Generated by Django 4.2.20 on 2025-03-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('analysis', models.JSONField(verbose_name='Анализ данных')),
            ],
            options={
                'verbose_name': 'Анализированный отзыв',
                'verbose_name_plural': 'Анализированные отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-request_datetime'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='request',
            name='car_brand',
            field=models.CharField(max_length=100, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='request',
            name='car_model',
            field=models.CharField(max_length=100, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='request',
            name='component_ratings_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Оценки компонентов'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='search_criteria',
            field=models.TextField(default=1, verbose_name='Критерии поиска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='top_ads_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Топ объявлений'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
