# Generated by Django 4.2.20 on 2025-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_analyzedreviews_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedreviews',
            name='analysis',
            field=models.TextField(verbose_name='Анализ данных'),
        ),
    ]
