# Generated by Django 4.2.20 on 2025-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_analyzedreviews_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedreviews',
            name='analysis',
            field=models.JSONField(verbose_name='Анализ данных'),
        ),
    ]
