# Generated by Django 4.2.20 on 2025-04-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ratings_plot',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение графика оценок'),
        ),
        migrations.AddField(
            model_name='request',
            name='semantic_plot',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение семантического анализа'),
        ),
    ]
